DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS topic;


CREATE TABLE topic
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	primary key (id)
) 
ENGINE=InnoDB;

ALTER TABLE topic ADD UNIQUE INDEX UQ_name (name);


CREATE TABLE news
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	topic_id INT UNSIGNED NOT NULL,
	name VARCHAR(50) NOT NULL,
	publication_date DATETIME NOT NULL,
	txt LONGTEXT,
	primary key (id)
)
ENGINE=InnoDB;

ALTER TABLE news ADD FOREIGN KEY (topic_id) REFERENCES topic(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
